name: Python CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Using
        run: |
          pip install make
          pip install NPM
          pip install NodeJS
          make setup
          make install
          make build
          make start
      - name: Run tests
        run: |
          make test
      - name: Run linter
        run: |
          make lint
